version: "2.1"
services:
  mydb:
    image: opavlova/db-hsqldb
    container_name: my-hsqldb-for-hibernate-accept-project
    ports:
    - "9001:9001"
    command: hsqldb

# jdbc:hsqldb:hsql://localhost:9001/test
#  Username: sa, Password :


#It is BusyBox v1.24.2   image
